// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGt707h-1EqTVKU07wgNQKukg3bUfgzTM',
    appId: '1:373318686902:web:d88f0493a04e664be9ae17',
    messagingSenderId: '373318686902',
    projectId: 'assignment-965e2',
    authDomain: 'assignment-965e2.firebaseapp.com',
    storageBucket: 'assignment-965e2.firebasestorage.app',
    measurementId: 'G-W02233M00Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAakcygB13uTfnhmMShsGmA7hHCtNZ6ziM',
    appId: '1:373318686902:android:0296d64e6d4994d0e9ae17',
    messagingSenderId: '373318686902',
    projectId: 'assignment-965e2',
    storageBucket: 'assignment-965e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd0JQhcfiCAIIvVWhSAsWHU61crcKucqw',
    appId: '1:373318686902:ios:2ea5bb25ae83f2e4e9ae17',
    messagingSenderId: '373318686902',
    projectId: 'assignment-965e2',
    storageBucket: 'assignment-965e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterWidgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd0JQhcfiCAIIvVWhSAsWHU61crcKucqw',
    appId: '1:373318686902:ios:2ea5bb25ae83f2e4e9ae17',
    messagingSenderId: '373318686902',
    projectId: 'assignment-965e2',
    storageBucket: 'assignment-965e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterWidgets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGt707h-1EqTVKU07wgNQKukg3bUfgzTM',
    appId: '1:373318686902:web:b4eac3ad9045a7a5e9ae17',
    messagingSenderId: '373318686902',
    projectId: 'assignment-965e2',
    authDomain: 'assignment-965e2.firebaseapp.com',
    storageBucket: 'assignment-965e2.firebasestorage.app',
    measurementId: 'G-GM2V322PXV',
  );
}
